### ISSUE TITLE
Host on GitHub Pages

### ISSUE THREAD

**Issue by piperswe** [ztaylor54/code-editor#11]
You can host the latest version on GitHub Pages by:
1. Creating a branch named `gh-pages`
2. Changing the default branch to `gh-pages`
3. Renaming `code-editor.html` to `index.html`
4. Deleting `.gitignore`

This is just a suggestion, but it would make the tool much more useful.

**Comment by ztaylor54** [comment]
I've considered it, it would be nice to be able to use it from anywhere. Let me look into it.

**Comment by ztaylor54** [comment]
Doesn't work, 404ing on all resources.

**Comment by piperswe** [comment]
You've got to push the `node_modules` folder to gh_pages, I can PR it if you want

**Comment by ztaylor54** [comment]
I figured that out just now :)

**Comment by ztaylor54** [comment]
This is absolutely fantastic! Exactly what I wanted.

**Comment by piperswe** [comment]
Now all that's left is making `gh-pages` the default branch and removing `master`, then the latest version will always be on GH Pages.

**Comment by ztaylor54** [comment]
Won't there be no need for `npm install` anymore? If I delete `master`, then would we be assuming the tool would be solely used online?
