### ISSUE TITLE
normalize.css and docs.css missing from node_modules

### ISSUE THREAD

**Issue by ztaylor54** [ztaylor54/code-editor#5]
The npm dependencies are missing docs.css and normalize.css.  
Errors:  

```
file:///C:/Users/Zachary/Documents/GitHub/code-editor/node_modules/normalize.css/normalize.css 
Failed to load resource: net::ERR_FILE_NOT_FOUND
```

```
file:///C:/Users/Zachary/Documents/GitHub/code-editor/node_modules/codemirror/doc/docs.css  
Failed to load resource: net::ERR_FILE_NOT_FOUND
```

**Comment by piperswe** [comment]
I'll fix that right now!

On Mon, Nov 16, 2015 at 4:49 PM, Zachary Taylor notifications@github.com
wrote:

> The npm dependencies are missing docs.css and normalize.css.
> 
> Errors:
> 
> file:///C:/Users/Zachary/Documents/GitHub/code-editor/node_modules/normalize.css/normalize.css
> Failed to load resource: net::ERR_FILE_NOT_FOUND
> 
> file:///C:/Users/Zachary/Documents/GitHub/code-editor/node_modules/codemirror/doc/docs.css
> Failed to load resource: net::ERR_FILE_NOT_FOUND
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ztaylor54/code-editor/issues/5.

## 

Zebulon McCorkle
a.k.a. ClassCoder
http://classcoder.com
zeb@classcoder.com

**Comment by piperswe** [comment]
It seems `docs.css` isn't needed, it doesn't do anything really. I forgot to add Normalize to the `package.json`, that's why it's not working.
