### ISSUE TITLE
This project doesn't have a license.

### ISSUE THREAD

**Issue by piperswe** [ztaylor54/code-editor#6]
I'd suggest ISC or GPL, depending on 1. where you got the original code from and 2. what you'd like in the license.

**Comment by ztaylor54** [comment]
I'll get on that.

**Comment by ztaylor54** [comment]
https://github.com/codemirror/CodeMirror/blob/master/LICENSE

Here's the license for code mirror. Their only requirement is that the copyright statement be carried over.

**Comment by piperswe** [comment]
CodeMirror has the MIT license, which is a slightly modified ISC license and is also compatible with GPL. It's your call what license.

**Comment by ztaylor54** [comment]
Licensed under GNU General Public License.
